version: '3'

services:
  # Base services from main docker-compose.yml (duplicated for standalone usage)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped

  # Spark master node
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8180:8080"  # Web UI
      - "7077:7077"  # Spark master port
    volumes:
      - ./spark-apps:/opt/spark/apps
      - ./spark-data:/opt/spark/data
      - ./logs:/opt/spark/logs
    restart: unless-stopped

  # Spark worker node
  spark-worker:
    image: bitnami/spark:3.4.1
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark-apps:/opt/spark/apps
      - ./spark-data:/opt/spark/data
      - ./logs:/opt/spark/logs
    restart: unless-stopped

  # Kafka-Spark streaming processor
  spark-streaming:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-streaming
    depends_on:
      - spark-master
      - kafka
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=security-events
    volumes:
      - ./spark-apps:/opt/spark/apps
      - ./spark-data:/opt/spark/data
      - ./logs:/opt/spark/logs
    restart: unless-stopped

  # Event generator
  generator:
    build:
      context: .
      dockerfile: Dockerfile.generator
    container_name: security-events-generator
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: security-events
      EVENT_GENERATION_INTERVAL: 1.0
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data: 